Signals: Handle `KeyError` for no date for live_data
numerai/example-scripts pull request #58
Opened 2020-12-31 15:28 UTC by parmarsuraj99

If there is no date in `full_data` for `date_string`, copy the structure of `full_data` for later concatenation with `thursday_data`.

2021-01-07 20:18 UTC, jeethu requested changes
Thanks for the PR @parmarsuraj99 ! I've got one minor nit.

2021-01-07 20:18 UTC, jeethu commented on signals/example_model.py
> +        live_data = pd.DataFrame(columns=full_data.reset_index().columns).set_index('date')
This could be simpler.
```suggestion
        live_data = full_data.iloc[:0].copy()
```

2021-01-08 15:25 UTC, parmarsuraj99 commented on signals/example_model.py
> +        live_data = pd.DataFrame(columns=full_data.reset_index().columns).set_index('date')
Thanks @jeethu . Committed.

2021-01-08 15:39 UTC, jeethu commented
Great! @parmarsuraj99 Now, could I ask you to squash those 3 commits into a single commit? 🙂

2021-01-09 10:51 UTC, jeethu approved these changes
LGTM!

2021-01-09 16:10 UTC, michael-phillips-data commented
Thanks you so much both of you :)

2021-01-09 16:10 UTC, merged