iexcloud v0.1
numerai/example-scripts pull request #72
Opened 2021-03-25 11:29 UTC by jorijnsmit

It was mentioned in one of the Signals roundtables that there's a bounty on more example scripts, especially ones that incorporate new API data sources. I took this opportunity to get familiar with Signals while open sourcing my attempts/learnings.

Here's a first version of my example script which uses data from the [IEX Cloud API](https://iexcloud.io/docs/api/) through the Python wrapper [`iexfinance`](https://addisonlynch.github.io/iexfinance/stable/about.html). Note that I am using the free version and its sandbox option. There is no guarantee the actual data is reliable!

I also had to extend the existing tickers map with some more ID types in order to retrieve data properly from IEX. So far this is only done for the US region but my goal is to do this for all provided tickers eventualy.

Any feedback is welcome, I'd love to continue turning this into a proper example/signal!

2021-03-26 22:28 UTC, LiamHz requested changes

2021-03-26 22:28 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +map = pd.read_parquet('signals/iexcloud/extended_map_us.parquet')
I think the code used to generate this parquet (`extended_map_us.ipynb`) should be moved into `dividends.py`.  We could still check if the file exists via `os.path.exists()` or something similar, and only generate if it doesn't exist.

2021-03-26 22:28 UTC, LiamHz commented on signals/iexcloud/extended_map_us.ipynb
> +    "    iex.append(refdata.get_region_symbols(region=region))\n",
When running `refdata.get_region_symbols(region=region)` I get this error

`ConnectionError: HTTPSConnectionPool(host='sandbox.iexapis.com', port=443): Max retries exceeded with url: /stable/ref-data/region/US/symbols?token=XXXXXXXXX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9ba5904f98>: Failed to establish a new connection: [Errno 110] Connection timed out',))`

I'm guessing this is because I'm running this without a valid IEX api token
```python
os.environ['IEX_TOKEN'] = 'XXXXXXXXX'
os.environ['IEX_API_VERSION'] = 'iexcloud-sandbox'
```

I'll DM you on RocketChat about getting an API key

2021-03-26 22:28 UTC, LiamHz commented on signals/iexcloud/extended_map_us.ipynb
> +    "from iexfinance import refdata\n",
I'd add this to the beginning of your notebook
`!pip install iexfinance`

2021-03-26 22:28 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +    os.environ['IEX_API_VERSION'] = 'iexcloud-sandbox'
Could you add a README similar to the one for the [Quandl example script](https://github.com/numerai/example-scripts/tree/master/signals/quandl)

Some things to include:
- What is IEX finance?
- Is it a paid service?
- How do I get an API key?
- What's this script doing / what's the "signal" it's picking up on? (quick overview)

2021-03-26 22:28 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +            joined = prices.resample('D').ffill().join(dividends.resample('D').ffill()).ffill()
Forward fill is a bit worrying. Could we print out some info on how many values had to be filled using this method?

2021-03-26 22:28 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +# what is corr of signal with target?
Good question. Let's print out the mean validation correlation the predictions. Would also be cool if you submit the predictions from this script and attach screenshots of your model diagnostics

2021-04-05 21:53 UTC, LiamHz requested changes
Am blocked with testing due to `ConnectionError`s, details in my review comments

2021-04-05 21:53 UTC, LiamHz commented on signals/iexcloud/dividends.ipynb
> +    "if ('NUMERAI_PUBLIC_ID' not in os.environ) & ('NUMERAI_SECRET_KEY' not in os.environ):\n",
```suggestion
    "if ('NUMERAI_PUBLIC_ID' not in os.environ) and ('NUMERAI_SECRET_KEY' not in os.environ):\n",
```

2021-04-05 21:53 UTC, LiamHz commented on signals/iexcloud/dividends.ipynb
> +    "    os.environ['IEX_API_VERSION'] = 'stable'"
```suggestion
    "os.environ['IEX_TOKEN'] = 'XXXXXXXXX'\n",
    "os.environ['IEX_API_VERSION'] = 'iexcloud-sandbox' if SANDBOX else 'stable'\n",
```
Does IEX_TOKEN change with SANDBOX? If not, we can use this

Also, it's not clear to me if I should set IEX_TOKEN to my "secret" or "publishable" token

2021-04-05 21:53 UTC, LiamHz commented on signals/iexcloud/dividends.ipynb
> +    "    os.environ['NUMERAI_SECRET_KEY'] = 'XXXXXXXXX'\n",
We should make a single cell at the very beginning of the notebook where all the config variables are set by the user. Similar change should be made in the `.py` file as well

2021-04-05 21:53 UTC, LiamHz commented on signals/iexcloud/dividends.ipynb
> +    "print(f\"retrieved usable dividend data for {full_data['bloomberg_ticker'].unique().size} symbols.\")"
This times out and throws the following error when I run it
```
ConnectionError: HTTPSConnectionPool(host='sandbox.iexapis.com', port=443): Max retries exceeded with url: 
/stable/stock/market/batch?symbols=MLCO&types=dividends&range=5y&token=sk_d4bce1dc142642fa947585c76164b60c
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe5156d04e0>:
Failed to establish a new connection: [Errno 110] Connection timed out',))
```

2021-04-05 21:53 UTC, LiamHz commented on signals/iexcloud/dividends.ipynb
> +    "print(f\"retrieved usable dividend data for {full_data['bloomberg_ticker'].unique().size} symbols.\")"
Happens regardless of if I set my IEX_TOKEN to the "secret" or "publishable" key

2021-04-11 11:58 UTC, jorijnsmit commented on signals/iexcloud/dividends.ipynb
> +    "    os.environ['IEX_API_VERSION'] = 'stable'"
`IEX_TOKEN` is different for sandbox or stable. I'll add a note explaining.

2021-04-21 22:51 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +                break
Why are we capping the number of dividends to grab at 10? Just to speed up execution?

2021-04-21 22:52 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +print(f"retrieved usable dividend data for {full_data['bloomberg_ticker'].unique().size} symbols")
```suggestion
print(f"retrieved usable dividend data for {full_data['bloomberg_ticker'].nunique()} symbols")
```

2021-04-21 22:55 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +napi.upload_predictions('submission.csv', model_id=napi.get_models()['XXXXXXXXX'])
Let's make MODEL_NAME a variable and have it defined up at the top where numerapi token is defined
```suggestion
napi.upload_predictions('submission.csv', model_id=napi.get_models()[MODEL_NAME])
```

2021-04-21 22:57 UTC, LiamHz requested changes

2021-04-21 22:57 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +                break
Why are we capping the number of stocks with dividends we retrieve to 10? Just to speed up runtime?

2021-04-21 22:57 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +print(f"retrieved usable dividend data for {full_data['bloomberg_ticker'].unique().size} symbols")
```suggestion
print(f"retrieved usable dividend data for {full_data['bloomberg_ticker'].nunique()} symbols")
```

2021-04-21 22:57 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +napi.upload_predictions('submission.csv', model_id=napi.get_models()['XXXXXXXXX'])
Let's make MODEL_NAME a variable and have it defined up at the top where numerapi token is defined
```suggestion
napi.upload_predictions('submission.csv', model_id=napi.get_models()[MODEL_NAME])
```

2021-04-21 23:12 UTC, jorijnsmit commented on signals/iexcloud/dividends.py
> +                break
good catch, this should only be used for testing purposes

2021-04-21 23:14 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +
```suggestion
MODEL_NAME = 'XXXXXXXXX'

```

2021-04-22 17:15 UTC, LiamHz requested changes
Last round of change requests!

2021-04-22 17:15 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +            # TODO: filter out any stocks that used to pay out dividends but do not anymore
```suggestion
            # NOTE: Stocks that used to payout dividends but do not anymore are not filtered out
```

2021-04-22 17:15 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +# TODO: compare Friday's signal (asfreq) with other weekly aggregates
```suggestion
```

2021-04-22 17:15 UTC, LiamHz commented on signals/iexcloud/dividends.ipynb
> +    "            # TODO: filter out any stocks that used to pay out dividends but do not anymore\n",
```suggestion
    "            # NOTE: Stocks that used to payout dividends but do not anymore are not filtered out\n",
```

2021-04-22 17:15 UTC, LiamHz commented on signals/iexcloud/dividends.ipynb
> +    "# TODO: compare Friday's signal (asfreq) with other weekly aggregates\n",
```suggestion
```

2021-04-22 20:09 UTC, jorijnsmit commented
Accepted.

2021-04-23 18:40 UTC, LiamHz approved these changes

2021-04-23 18:40 UTC, LiamHz commented on signals/iexcloud/dividends.py
> +        # use a range of up to 5y for extended backtesting of the validation set
```suggestion
        # use a range of up to 1y for extended backtesting of the validation set
```

2021-04-23 18:40 UTC, LiamHz commented on signals/iexcloud/dividends.ipynb
> +    "        # use a range of up to 5y for extended backtesting of the validation set\n",
```suggestion
    "        # use a range of up to 1y for extended backtesting of the validation set\n",
```

2021-04-23 18:41 UTC, merged